#About me
print("Hello there")
print("Hello")
print("How are you doing?")
print("I'm doing well")
print("What is your name?")
print("My name is Dibora")
print("Where are you from?")
print("I'm from Nairobi")
print("It is nice to meet you, Diborah")
print("Nice to me you too")